services:

  db:
    image: postgres:18.0-alpine3.22
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nodebot
    volumes:
      - db-data:/var/lib/postgresql/18/docker

volumes:
  db-data:
