name: Tests
on: [push]

jobs:
  unit:
    name: unit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: "1.25.0"
      - name: Run unit tests
        run: go test -v --bench --benchmem ./...
